/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import { useFrame } from 'react-three-fiber'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('assets/3objects.gl.gltf')

  const cube = useRef()

  useFrame(() => {
    cube.current.rotation.x = cube.current.rotation.y += 0.01
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['StandardA88744.002']} geometry={nodes.s0010.geometry} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        material={materials['Reflective4A7C47.002']}
        geometry={nodes.p0011.geometry}
        position={[0.01, 0.14, -0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Standard9C5AA9.002']}
        geometry={nodes.p0012.geometry}
        position={[-0.01, 0.17, 0.11]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        ref={cube}
        material={materials['Flat4A5E8B.002']}
        geometry={nodes.p0013.geometry}
        position={[0.21, 0.13, -0.04]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('assets/3objects.gl.gltf')
